### ISSUE TITLE
(debian) dependencies missing

### ISSUE THREAD

**Issue by Seegras** [xtaran/dist-detect#1]
Hi

I had to install libio-socket-inet6-perl, libnet-cidr-set-perl and libmojo-sqlite-perl, libfile-touch-perl, libdata-printer-perl,  libdpkg-parse-perl to work on debian; still missing is YAML/Any.pm  which is not yet available in debian. 

Anyway, it would be nice to have a debian dependencies-list, at least in a README, so we'd know what we had to install

**Comment by xtaran** [comment]
> it would be nice to have a debian dependencies-list, at least in a README

A complete Debian packaging is planned, once the directory layout and file names are expected to no more change (and an upstream build/installation system has been put in place).

But granted, before that, it should be put into the README. Will do.

> still missing is YAML/Any.pm which is not yet available in debian.

It's available in Debian since at least Debian 8 Jessie. It's part of the `libyaml-perl` package.
